apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
    jenkins/label: jnlp-agent
  name: jnlp-agent
spec:
  containers:
    - image: ccr.ccs.tencentyun.com/my-registry/jenkins:salve-gradle
#    - image: jicki/jenkins-jnlp:gradle5.6
      imagePullPolicy: Always
      name: jnlp
      tty: true
      volumeMounts:
        - mountPath: /usr/bin/kubectl
          name: volume-3
          readOnly: false
        - mountPath: /var/run/docker.sock
          name: volume-1
          readOnly: false
        - mountPath: /usr/bin/docker
          name: volume-0
          readOnly: false
        - mountPath: /root/.kube
          name: volume-2
          readOnly: false
        - mountPath: /home/jenkins/agent
          name: workspace-volume
          readOnly: false
        - mountPath: /root/.gradle
          name: volume-4
  restartPolicy: Never
  serviceAccount: jenkins
  volumes:
    - hostPath:
        path: /usr/bin/docker
      name: volume-0
    - hostPath:
        path: /root/.kube/
      name: volume-2
    - hostPath:
        path: /var/run/docker.sock
      name: volume-1
    - emptyDir:
        medium: ""
      name: workspace-volume
    - hostPath:
        path: /usr/bin/kubectl
      name: volume-3
    - hostPath:
        path: /opt/data/gradle
      name: volume-4