apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-product-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-product-app
    spec:
      containers:
        - name: example-product-app
          image: {{ docker_image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: actuator
              containerPort: 9091
              protocol: TCP