spring:
  datasource:
    url: jdbc:mysql://52.184.90.238:3306/example_db?characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true&&nullCatalogMeansCurrent=true
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"
